<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- PDF engines -->
    <PackageVersion Include="bblanchon.PDFium.Win32" Version="156.0.8076" />
    <PackageVersion Include="PDFsharp-WPF" Version="6.2.4" />
    <!-- UI -->
    <PackageVersion Include="WPF-UI" Version="4.3.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <!-- Tests -->
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
